# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termishare < Formula
  desc "Peer to peer terminal sharing"
  homepage "https://github.com/qnkhuat/termishare"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qnkhuat/termishare/releases/download/v0.0.4/termishare_0.0.4_MacOS_x86_64.tar.gz"
      sha256 "b9ce679e668ca88b5219ceedf621f0ca688a7fa99f96b08dba6d3a3418b34b27"

      def install
        bin.install "termishare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qnkhuat/termishare/releases/download/v0.0.4/termishare_0.0.4_MacOS_arm64.tar.gz"
      sha256 "eca4330092194d358be9c39e88c83688d6100640981669310021e4259b9ecea0"

      def install
        bin.install "termishare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qnkhuat/termishare/releases/download/v0.0.4/termishare_0.0.4_Linux_arm64.tar.gz"
      sha256 "e01625ff6e8c19627782377948614e5adaea5deb84691a9a5f857bbf648a3e11"

      def install
        bin.install "termishare"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/qnkhuat/termishare/releases/download/v0.0.4/termishare_0.0.4_Linux_x86_64.tar.gz"
      sha256 "d412584d5f82c50bd0b20fe86a61435bba30fad54b7768efa780bd22a755c087"

      def install
        bin.install "termishare"
      end
    end
  end
end
